### ISSUE TITLE
applicationDidLaunch/applicationDidTerminate support

### ISSUE THREAD

**Issue by sanmadjack** [BarRaider/streamdeck-tools#14]
Are there any plans to add support for the monitored application lifetime events?

https://developer.elgato.com/documentation/stream-deck/sdk/events-received/#applicationdidlaunch

**Comment by BarRaider** [comment]
Hey @sanmadjack,
That actually already exists.
You can subscribe to such events from your plugin like this:
`Connection.StreamDeckConnection.OnApplicationDidTerminate += StreamDeckConnection_OnApplicationDidTerminate;`

(Don't forget to unsubscribe in the Dispose function).
If you need any more help or have suggestions, feel free to drop to our Discord server where we have a #developers-chatroom 
http://discord.barraider.com
