### ISSUE TITLE
Missing onAppear and onDisappear events

### ISSUE THREAD

**Issue by Wolverine80** [BarRaider/streamdeck-tools#19]
Hi,

I was happy to see that the StreamDeck events made available in the API, but the two most interesting, onAppear and onDisappear, are not included.
I would have used them to open and close a websocket connection to another server, that otherwise would not be initiated because I don't use the onTick action in favor of an event based trigger in this module.

**Comment by BarRaider** [comment]
Hi @Wolverine80 ,

Since SDTools wraps your plugin OnWillAppear automatically triggers your constructor OnWillDisappear calls your Dispose function.

**Comment by Wolverine80** [comment]
Oh, that's cool. Thanks for the info.
