### ISSUE TITLE
NON ISSUE (QUESTION): Is there a way to SEND events with this?

### ISSUE THREAD

**Issue by ivanpointer** [BarRaider/streamdeck-tools#23]
I'm a software engineer who loves to automate everything.  Specifically, I'm wanting to setup global hotkeys with a chording (or chaining) approach, like in Visual Studio - creating global hotkeys that require two subsequent hotkey presses.  For example, in Visual Studio, to run all tests in the Test Explorer, you'd first press [Ctrl+R], then [A].

The problem isn't the chording; AutoHotkey (AHK), while crude, facilitates this behavior quite well.

Here's what I'm after:

A hotkey triggered in AHK would send a global event on the operating system, that `MyPlugin : PluginBase` would listen for.  When that event is triggered, `MyPlugin` would send the `switchToProfile` event to the Stream Deck, switching the profile.

According to Elgato's documentation, you are able to send this event: `switchToProfile`:

https://developer.elgato.com/documentation/stream-deck/sdk/events-sent/#switchtoprofile

Is this possible with the library, as is?

If no - would you mind inviting me as a contributor so I can add this functionality and submit a PR for it?

Thanks!
NullPointerExpert (NPE)

**Comment by ivanpointer** [comment]
I found it on the `SDConnection` class.

Nevermind me.

Great work BarRaider!  You're a legend :D

**Comment by BarRaider** [comment]
Please note the SDK limits using SwitchToProfile only to profiles your plugin created. 
But yes, the library supports all the features in the SDK.
