### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Nolanrulesroblox** [BarRaider/streamdeck-tools#25]
Full log [log.txt](https://github.com/BarRaider/streamdeck-tools/files/4836211/log.txt)

Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 6/26/20
Scan Time: 2:39 AM
Log File: fca54a70-b790-11ea-8bb9-dcf5050d6df8.json

-Software Information-
Version: 4.1.0.56
Components Version: 1.0.955
Update Package Version: 1.0.26041
License: Premium

-System Information-
OS: Windows 10 (Build 19041.329)
CPU: x64
File System: NTFS
User: System
-Scan Options-
Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 1
Malware.Generic.4171343795, C:\USERS\@@@@@\APPDATA\ROAMING\ELGATO\STREAMDECK\PLUGINS\COM.BARRAIDER.WINTOOLS.SDPLUGIN\COM.BARRAIDER.WINTOOLS.EXE, No Action By User, 1000000, 0, , , , 

Module: 1
Malware.Generic.4171343795, C:\USERS\@@@@\APPDATA\ROAMING\ELGATO\STREAMDECK\PLUGINS\COM.BARRAIDER.WINTOOLS.SDPLUGIN\COM.BARRAIDER.WINTOOLS.EXE, No Action By User, 1000000, 0, , , , 

File: 2
Malware.Generic.4171343795, C:\USERS\@@@@@\APPDATA\ROAMING\ELGATO\STREAMDECK\PLUGINS\COM.BARRAIDER.WINTOOLS.SDPLUGIN\COM.BARRAIDER.WINTOOLS.EXE, No Action By User, 1000000, 0, 1.0.26041, 000C5276FE1DEE47F8A1A7B3, dds, 00780740
Malware.Generic.4171343795, C:\USERS\NRRINC\APPDATA\LOCAL\TEMP\COM.BARRAIDER.WINTOOLS.STREAMDECKPLUGIN, No Action By User, 1000000, 0, 1.0.26041, 000C5276FE1DEE47F8A1A7B3, dds, 00780740

**Comment by BarRaider** [comment]
False positive, happens occasionally unfortunately
