### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by ghost** [BarRaider/streamdeck-tools#26]
Hi there,

I'm not sure if there is already something like that and I just couldn't find it.

I'm writing some plugins that should act as folders for other plugins.
I.e. the display is custom, but when pressing the button you should enter a folder.
Currently, I'm solving this with separate profiles, but this is very inconvenient.

Best regards,
Kc

**Comment by BarRaider** [comment]
The current Stream Deck SDK does not support such features. Creating something similar to what you want in the current SDK is problematic as:
1. You have to create profiles for each "folder" which means there is a hard limit on the number of folders.
2. Each of these profiles is shown on the user's Stream Deck app, thus flooding them with a bunch of unwanted profiles.

I recommend you reach out to Elgato directly to ask for a scalable solution for such a feature.
