### ISSUE TITLE
Question regarding the possibility to implement unit testing

### ISSUE THREAD

**Issue by VictorGrycuk** [BarRaider/streamdeck-tools#33]
Hi, I have been using StreamDeck Tools for a while now. So first of all, thank you for this awesome wrapper 🙂.

The more plugin I write, the more I to want to add unit/ tests to make sure everything is working as expected.
But the current implementation of the [PluginBase](https://github.com/BarRaider/streamdeck-tools/blob/master/barraider-sdtools/Tools/PluginBase.cs) class makes it hard to decouple the [SDConnection](https://github.com/BarRaider/streamdeck-tools/blob/master/barraider-sdtools/Backend/SDConnection.cs) class, such as making the SDConnection an interface in order to be able to inject a mocked SDConnection.

That would allow me to separate the logic of the plugin itself from the StreamDeck connection, pass custom plugin/device configuration, etc.

So I guess my question is that if you plan to implement this kind of changes in the short to medium time frame (if at all), or some kind of testing framework around it, or possible at all.

Thank you.

Edit: I went ahead, cloned the repository, and implemented `ISDConnection` interface. Built my plugins with it and so far they work fine. I'll be testing how useful it is for unit testing.

**Comment by BarRaider** [comment]
Hi, 

Did this solve your issue?

**Comment by VictorGrycuk** [comment]
Hi @BarRaider,
Actually, yes. I did these modifications to the StreamDeck-Tools project:
- Created an interface called `ISDConnection` that implements everything used in `SDConnection` class.
- I made `SDConnection` implement the `ISDConnection` interface
- I modified `PluginBase` class to receive and use the `ISDConnection` interface instead of the `SDConnection` class

Once these modifications were made, I rebuilt the StreamDeck-Tools project, installed the modified nuget package, created a new unit tests project on my plugin project, and created the `MockedConnection` class that implements `ISDConnection` interface. 

While I haven't had much time to fully test everything, this has allowed me to test that the correct image is being set when calling `SetImageAsync` by implementing a custom logic inside `MockedConnection`. It also allows working on a plug in without having the streamdeck around, since it allows the emulation of `KeyPressed`, `KeyReleased`, `ReceivedSettings`, etc.

Do you plan on implementing these changes in future releases? Do you accept pull requests? I dont mind creating a pull requests with the modifications detailed at the start of the comment.

Regards.

**Comment by BarRaider** [comment]
I have something similar, but yeah, you can send over a pull request so I can verify it includes everything

**Comment by BarRaider** [comment]
Resolved in release 3.2
