### ISSUE TITLE
No plugin found that matches action

### ISSUE THREAD

**Issue by IslandJohn** [BarRaider/streamdeck-tools#34]
I'm getting this error in the pluginlog: https://pastebin.com/GCCJx08p

Everything seems correct, but I'm sure it's something silly. Here's my manifest: https://pastebin.com/CcTbg6wQ

What am I missing here?

**Comment by BarRaider** [comment]
Do you have the following in your action cs file?

```
[PluginActionId("net.islandjohn.fsuipc.virtualbutton")]
public class MyPlugin : PluginBase
```

**Comment by IslandJohn** [comment]
That annotation is probably what I missed, thanks. I'll close this issue once I verify.
