### ISSUE TITLE
key routine for handling 2.7 images

### ISSUE THREAD

**Issue by plasticMAYHEM2028** [BarRaider/streamdeck-tools#36]

**Comment by BarRaider** [comment]
Hi, this is extremely long and I could not understand what the actual problem/issue is.
Can you give a very short explanation of the problem? i.e "I am trying to do X by calling function Y, I expected that Z will happen but what actually happens is W"

**Comment by plasticMAYHEM2028** [comment]
how do you delete these things - i left it up because it seemed rude to spend half an hour on it then delete it
was twice as long as it should have been

**Comment by BarRaider** [comment]
No worries, closed.
