### ISSUE TITLE
synopsis of last request -- [sigh]

### ISSUE THREAD

**Issue by plasticMAYHEM2028** [BarRaider/streamdeck-tools#37]
ok so that was not stream of conscious. yet. spent like 3 hours making sure i got all the details right.

1) cannot make a button display without calling a key routine
2) key routine takes a reference, the new "out" type - and then , thats just a draw thing
3) returns a bitmap, which is dubious to out? usage? unless its because its static
4) if you set the bitmap to null there is no button display
5) all i see is that it takes a draw thing, which never exposes its original file load\\image
6) secondly that it sends back a bitmap with no attachment or association with anything specific
7) unless this is a super-class that is inhereting another class, with transparent usage of the underlaying function
8) i see it makes a new var, local to the function\class (static of course) - i mean that is local so - t.f.

i do not get this image handling thing ----------------- i am fairly sure i 80% get out - but i mean you only need 40 to use it

**Comment by plasticMAYHEM2028** [comment]
damn see that's only marginally better than my original post -- see i do know english !

**Comment by plasticMAYHEM2028** [comment]
TRYING AGAIN -- what is the role ! of the duplicity - of the 3 -response function, the plastic one --
its GenerateKeyImage GenerateGenericKeyImage GenerateKeyImage

its duplicitous, i believe out means that a "new" reference is passed, with new options? so the function inherits the drawer
(which is not an image)
then the bitmap that is returned isnt even affixed or addressed anywhere t.f. ? its using a local var name ----------- ?

i dont get output to graphics which is nothing and output to bitmap - which is the 2nd YET also! not addressed/cataloged -- ??
*whispers* is it a super-class - that is transparent ?

**Comment by plasticMAYHEM2028** [comment]
drawer == Graphics ---------- its complicated how its related to forms, but obviously# noformshere#

**Comment by BarRaider** [comment]
Trying to understand your question, the difference between the functions is the type of Image created.
GenerateKeyImage will get a type of a stream deck and create an image that matches its resolution.  

GenerateGenericKeyImage will create a 144x144 image which is a good "neutral" scale for all types of Stream Decks

**Comment by plasticMAYHEM2028** [comment]
> Trying to understand your question, the difference between the functions is the type of Image created.
> GenerateKeyImage will get a type of a stream deck and create an image that matches its resolution.
> GenerateGenericKeyImage will create a 144x144 image which is a good "neutral" scale for all types of Stream Decks

right - but does it go to "out graphics" which is a drawer prepped with an image file (that apparently does not get recognized)
or is it passed back as a bitmap, which is what the return function does, then if you make that bitmap return equal null it wont display

so what is actually making it display? i assume it has to be sent through the web socket thing ?
my guess was super class or , "where is the web socket part" - 

the function inside those 3 functions seems to just make a blank black image - so - not getting it ?
if i dont call it though, my buttons dont display

was trying to get some time cut out of my schedule so i can get this released before NYE

**Comment by BarRaider** [comment]
The actual image is returned  from the function. The "out Graphics" parameter allows you to manipulate the currently empty image using the Graphics class.
At the end, the thing you want to pass to the Stream Deck is the return value of the function but if you just send it without manipulating it (using the Graphics object), you won't see anything as it's empty

**Comment by plasticMAYHEM2028** [comment]
> The actual image is returned from the function. The "out Graphics" parameter allows you to manipulate the currently empty image using the Graphics class.
> At the end, the thing you want to pass to the Stream Deck is the return value of the function but if you just send it without manipulating it (using the Graphics object), you won't see anything as it's empty

oh hell im stupid - can you just delete both these issues --- i was wrenching around because i spent like 30 hours straight refactoring, and my head was full of that
then this new stuff had no where to go lol

its not even the right part im looking at i want the setimageasync on connection and im a tard and totally forgot about it
it got deleted out of a 15 page long file coz thats what working with the audio interface does to pretty code ))):

thanks man !!!!!!!!!!!!!!!!!! quick responses awesome! unban me from the discord server next ;) ;) ;)
just delete this rabble, i cant do it it says you would have the options, over by "notifications" i think on the right

**Comment by plasticMAYHEM2028** [comment]
well hey if you want to chat - don't want to delete both -- lol . i got my blitting (TOLD YOU BRO) and its working
i gotta market#
i got no other choice -- if i don't survive .... its a few easy things .. yet ..................

totally different paradigms of thinking ### i couldnt handle it until i had the S\DECK
your cSHARP library lib function util wrapper on wrapper on free lib on - ARE WE LIBERAL YET
no
no we are Not.
this software gets my vision where it needs to go --- i have my blitting (THANK YOU BARRAIDER) working now
never seen before except in ; star wars - crazy birds ?
it was done in actionscript -- its the general idea - you draw to the buffer, then the buffer repeat(s) -- if you don't hit it #


lol
delete it bro
there's no use in taunting people with my NYE 2020 release -
i got x transform and y transform working flawlessly

i will release in four days with TWENTY OPTIONS -- for the dialface on the clock .............

**Comment by plasticMAYHEM2028** [comment]
no i mean you want """"murder death kill"""" as the main face

**Comment by plasticMAYHEM2028** [comment]
IGOTYOU#####
