### ISSUE TITLE
Text-alignment button Play/Pause

### ISSUE THREAD

**Issue by torstenweber** [BarRaider/streamdeck-tools#42]
The text of the "Play/Pause" button cannot be aligned to the top.

For illustration: In the image below, the "03:08" should be aligned at the top (the remaining time is the only value to be displayed).

![Spotify](https://user-images.githubusercontent.com/799205/106776235-2afd8880-6644-11eb-87be-7f43a3097de1.png)

**Comment by BarRaider** [comment]
Correct, title at top and time remaining at bottom
