### ISSUE TITLE
profile load method -

### ISSUE THREAD

**Issue by vicarious1911** [BarRaider/streamdeck-tools#45]
hey couple things here - and as "usual" working on it RIGHT now so it's like duhhh

OK
1) found the profile load thing the comment says its for the buttons profile ???? tf is this
2) it does not load the profile by the name i give, that does exist (stream deck profile vs button profile ??)
3) afaik there is no way to get the button id or position from stream deck so if im in #1 at top left, it tells me ?
4) so i'm trying to load in an entire profile, and then if i have to i can do this with MSI installer or however

let me know i got like 5 minutes ): before i start plugging it in whatever way i can at the moment ............................. sigh
"useless internet"

could also make fun of those people that say "quote unquote" first
like cancelling out their entire point ----------
quote unquote "sarcastic finger marks"

pretty sure you dont want to say unquote anywhere near anything you want someone to remember (8

**Comment by vicarious1911** [comment]
got a joke here while working on my code - anything to pay for "services" (;

stream deck -- opens the way to the future with inclusion of XML Extensible Markup forms,
then, you put your configuration file name in there and, it's - got to be - html - extension?
lmao r.i.p. the extensible part of XML


total mechanical failure**

**Comment by vicarious1911** [comment]
json doesnt actually qualify as XML though does it - that might be a second joke ...

**Comment by vicarious1911** [comment]
"property inspector path - that includes the file name"
do you pop out on the other side of that file when you get there ......

**Comment by BarRaider** [comment]
There is no way to switch to a user-created profile, only to built-in plugin profiles. This is a Elgato Stream Deck limitation.
You can know which button you're on as you receive this in the Constructor as one of the settings
