### ISSUE TITLE
multiple config file issue ?

### ISSUE THREAD

**Issue by vicarious1911** [BarRaider/streamdeck-tools#46]
is this even a support thing? i'm a base coder too so i figured this would be for that , and not "use"

-- regardless

OK multiple buttons here, the same way you did yours - its in one of your packages at least -
then the json - then inside that the mandatory html file ; and inside that - also input

i see on the submission that you appear to marshal , and i cant tell if you went left or right - and it doesn't concern me
i dont need to make that call right now honestly

the thing is - when these three buttons are loaded they all have the same exact contents to the HTML config
because there's no identifying factors, and the input name itself yes but that i can change and the behavior does NOT

wait i had to explain that first and i missed the problem - 2 of 3 buttons dont load the input
i went through it , and right after i click submit i am deleting the config of the one that works to see if it shifts to one of the other two

**Comment by vicarious1911** [comment]
wow that actually did NOT work. wth.

**Comment by vicarious1911** [comment]
oh sorry i am being rude - my guess - i am looking at it now - is sdtools.common.js

**Comment by vicarious1911** [comment]
yeah this is killing me - update . i mean my tech goes $500 every minute so whatever.

worked in 1 did not work in 2 with exact same (local) config/file 1)
did not work when i removed the config from the one, so no cascade 2)
that means look in the source file(s) for each button 3)
there *is* nothing different in those two in regards to that 4)
that implies a namespace issue on the stream deck in the JSON file when its grouped with multiple HTML configs 5)
that is not only inside the streamdeck but also in javascript 6)

im quite willing to look at my code again because theres two paths there - which i could not label

and uh. neither one is looking legit . so.
*cough

**Comment by vicarious1911** [comment]
yup okay got it

the header file type declaration at the top of the button was not updated - the thing is
the behavior i got when testing "seems random" --- so this was to be expected;

the button that the input box works with - that one has the defaults in there its not even the right code
it works ):

then the other two same exact code and they did not work sigh. now that i fixed the PluginSettings class those two work perfect

and the third one still works with it not fixed )!~~~~~~~~~~~~~:

**Comment by BarRaider** [comment]
Dude, please stop spamming and please stop opening up fake issues.
If you need something, ask a very specific one-lined question. Otherwise, you're just spamming me and I'm going to ignore/close the ability to post questions
