### ISSUE TITLE
No Project License

### ISSUE THREAD

**Issue by VictorGrycuk** [BarRaider/streamdeck-tools#55]
Hi @BarRaider, I wanted to ask you if you plan to add a license to the project.
By [not having a license](https://choosealicense.com/no-permission/), we are not allowed to even include your library in our projects, which would defeat the purpose of the tool itself.

Thanks.

**Comment by adrian-miasik** [comment]
This library looks incredibly useful and I'd love to use it myself for plugin development, but as the issue stands: There's no license associated with the project.

@BarRaider , have you considered using a license or have you communicated the terms of using this project for our own plugins?

I'd love to give the library a go but I'm a bit reluctant as a result. There's an MIT licensed repo that allows me to create C# plugins but it seems a bit limiting and doesn't have many helper tools / methods.

Any info is appreciated.
Thanks for all the great plugins so far! :)

**Comment by BarRaider** [comment]
StreamDeck-Tools is MIT. I will add a license tomorrow
@adrian-miasik @VictorGrycuk

**Comment by adrian-miasik** [comment]
Awesome! (And what a blazing fast response too!)

I'm excited to try this out! Will give it a go later this afternoon. Thanks again! ❤️
