### ISSUE TITLE
Custom icons not an existing file on disk - DistributionTool 

### ISSUE THREAD

**Issue by BenjaminFourmaux** [BarRaider/streamdeck-tools#65]
Hi ! 👋 
I wanted to add custom icons to my plugin but when I run the .bat file, I get an error from the DistributionTool:
`Error: The action 'my.action' has an "Icon" property with the value 'icon-microphone-mute@2x.png' which is not an existing file on disk. Please add a valid value to the property "Icon" in the manifest.json` .
![Capture-console-distributiontool](https://user-images.githubusercontent.com/49273769/219447968-26eac2b4-ac03-49b3-b68e-14362ef87fee.PNG)

The icons are in the correct format (`72x72 & 144x144 for @2x`) and placed in the correct folder.

![Capture-vs-manifest](https://user-images.githubusercontent.com/49273769/219447974-37ff922e-2a61-4b39-afb9-68c35d01a573.PNG)

I build, clean and regenerate the project. Maybe I forget some things ?

Thank for your reply.

**Comment by Jaggernaut555** [comment]
Was having this similar issue. My problem ended up being that I had not changed the image property from `Do not copy` to `Copy if Newer` on the file properties
![image](https://user-images.githubusercontent.com/5661214/222981335-d83b59b7-f8e1-4104-be29-0b632b8b4e5d.png)
