### ISSUE TITLE
StreamDeck+ Unknown dialUp/dialDown event received

### ISSUE THREAD

**Issue by cvasquez-github** [BarRaider/streamdeck-tools#69]
`public override void DialPress(DialPressPayload payload)` is triggered properly but I'm getting an Event **dialUp** and **dialDown** **FATAL** log line _BarRaider.SdTools.Communication.StreamDeckConnection Unknown event received from Stream Deck_.

Using StreamDeck+ device, StreamDeck software version 6.1.0.18521, and StreamDeckTools 6.0.0.0 (NuGet)

**Comment by BarRaider** [comment]
Hi,
Elgato's Stream Deck SDK has changed.
New StreamDeckTools v6.1 is out (should be indexed in Nuget shortly) which introduces the new DialDown and DialUp events (and deprecates the DialPress event which is no longer supported).

**Comment by mhwlng** [comment]
streamdeck software 6.1.0.18521
StreamDeck-Tools" version="6.1.0" 

I now correctly receive the DialDown/DialUp events

but I'm now getting unknown dialpress event log errors ?

so it seems all 3 events are being sent ?

2023-04-25 11:46:43.2807|FATAL|com.mhwlng.starcitizen|8|BarRaider.SdTools.Communication.StreamDeckConnection Unknown event received from Stream Deck: {"action":"com.mhwlng.starcitizen.dial","context":"c247c4fcb5a1737760ed8610d18ab59c","device":"8F9F54D3085E17917873D7BA481EA6B7","event":"dialPress",

**Comment by cvasquez-github** [comment]
Same here, I can now use:
```
override void DialDown(DialPayload payload)
override void DialUp(DialPayload payload)
```
But now getting _Fatal BarRaider.SdTools.Communication.StreamDeckConnection Unknown event received from Stream Deck_ log line for  dialPress, pressed true and false.

**Comment by BarRaider** [comment]
Sorry, seems DialPress is deprecated but still being sent 🤷🏼‍♂️
v6.1.1 removes it from being logged
