### ISSUE TITLE
Cannot change title of Scene Switcher button

### ISSUE THREAD

**Issue by millerdq** [BarRaider/streamdeck-tools#70]
Running Streamdeck v6.1.0.18521  with OBS 29.9.0.
 
Cannot change the Title of Scene Switcher buttons.  When I add a new Scene Switcher button, the Title field says "disabled" and I cannot change it.  The buttons work, I just cannot re-label them.   Installed latest release of the plugin, but did not fix.  Any help would be appreciated.

![SharedScreenshot](https://user-images.githubusercontent.com/18232452/235379521-372f1f31-12f7-4321-97cf-ac4b5f651233.jpg)

**Comment by BarRaider** [comment]
It's by design. The scene name will show up on the key automatically.

**Comment by millerdq** [comment]
Uhh... But I want my Streamdeck title to be different than my OBS scene name.  Futhermore, I have many Streamdeck buttons using your Scene Switcher where OBS scene name and Streamdeck title NOT the same.  In the screenshot, ALL of the OBS scene names have a numeric suffix: 1 or 2, to identify the camera.  But, notice the Streamdeck titles are different from the OBS scene names.  what is going on?

**Comment by millerdq** [comment]
PS. Much thanks for attending responsively to this thread
