### ISSUE TITLE
Use of Framework 4.8.1

### ISSUE THREAD

**Issue by farangkao** [BarRaider/streamdeck-tools#71]
Just to report, that because of Barraider, the system was bugging me to install Framework 4.8.1 ,which seems not to be the default on all Windows 10 yet, and not needed for Stream Deck by Elegato.

Barraider seems the only Plugin that uses this Version, not sure if it is necessairy for the functionality.

However i had to remove the plugin for that reason.

Maybe you might consider downgrade to 4.8 if possible, since that is the version that 90% of all people have on their machines already.

Note: in some countries/windows versions therre might be already 4.8.1 active, but seems not everywhere.

**Comment by BarRaider** [comment]
.Net framework 4.8.1 has been out since August 2022.

Make sure your Windows is up to date. Install the latest Windows Update patches. Alternatively download the latest .Net Framework from here:
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481
